In [1]:
import pandas as po
import matplotlib.pyplot as plt

In [2]:
df = po.read_csv('../data/processed/imputation/edtwbi.csv')

In [3]:
df = df.drop(['num_zeros', 'FLAG'], axis=1)

In [4]:
df

,2014/1/1,2014/1/2,2014/1/3,2014/1/4,2014/1/5,2014/1/6,2014/1/7,2014/1/8,2014/1/9,2014/1/10,...,2016/10/22,2016/10/23,2016/10/24,2016/10/25,2016/10/26,2016/10/27,2016/10/28,2016/10/29,2016/10/30,2016/10/31
0,0.003306,0.005092,0.004084,0.002153,0.002118,0.002233,0.002193,0.002183,0.002754,0.002912,...,0.001007,0.000905,0.000711,0.000954,0.000763,0.000935,0.000706,0.000838,0.001079,0.001154
1,0.002839,0.002636,0.001719,0.000802,0.001172,0.001789,0.001347,0.001796,0.001463,0.001856,...,0.000434,0.000277,0.000536,0.000574,0.000536,0.000528,0.000357,0.000219,0.000523,0.000632
2,0.001043,0.001152,0.001260,0.000765,0.001356,0.001947,0.001788,0.002352,0.001590,0.002390,...,0.000379,0.000532,0.000389,0.000409,0.000522,0.000340,0.000028,0.000030,0.000123,0.000136
3,0.003647,0.004900,0.003473,0.002046,0.002234,0.002423,0.002611,0.004230,0.006640,0.008113,...,0.001479,0.001695,0.000921,0.000646,0.001120,0.000639,0.000595,0.000465,0.000907,0.000368
4,0.004756,0.004716,0.004660,0.002529,0.002707,0.003427,0.002706,0.003627,0.002892,0.003371,...,0.000977,0.001023,0.000833,0.001026,0.000962,0.000762,0.000782,0.000791,0.000898,0.001173
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24267,0.002694,0.002704,0.003149,0.001000,0.001347,0.001487,0.001405,0.002146,0.001875,0.001775,...,0.000548,0.000742,0.000437,0.000709,0.000591,0.000555,0.000415,0.000524,0.000627,0.000546
24268,0.000648,0.000892,0.000438,0.000416,0.000146,0.000177,0.000132,0.000161,0.000161,0.000514,...,0.000143,0.000141,0.000110,0.000206,0.000345,0.000106,0.000132,0.000133,0.000124,0.000172
24269,0.000073,0.000077,0.000051,0.000061,0.000089,0.000061,0.000043,0.000073,0.000014,0.000009,...,0.000389,0.000405,0.000338,0.000378,0.000241,0.000302,0.000230,0.000325,0.000367,0.000459
24270,0.000630,0.001240,0.001197,0.000547,0.000635,0.000717,0.000724,0.000964,0.000711,0.000819,...,0.000289,0.000482,0.000298,0.000466,0.000352,0.000280,0.000278,0.000308,0.000280,0.000481
24271,0.005606,0.002683,0.006354,0.003392,0.003885,0.004022,0.003971,0.005285,0.004280,0.004866,...,0.001687,0.001647,0.001464,0.001657,0.001579,0.001550,0.001655,0.001639,0.001434,0.001633